### ISSUE TITLE
Hardcode git output format

### ISSUE THREAD

**Issue by kvalo** [kvalo/pwcli#16]
Luca reported that commit fails for him. It was because he is using git's decorate feature. A quick workaround was to remove $ from this regexp:

        match = re.search(r'^commit ([0-9a-f]{40})$', text, re.MULTILINE)

A proper fix would be to use hardocoded output format, like --pretty=format:%H or something similar. And maybe --no-decorate?

**Comment by sukkachorn18** [comment]
> Luca reported that commit fails for him. It was because he is using git's decorate feature. A quick workaround was to remove $ from this regexp:
> 
> ```
>     match = re.search(r'^commit ([0-9a-f]{40})$', text, re.MULTILINE)
> ```
> 
> A proper fix would be to use hardocoded output format, like --pretty=format:%H or something similar. And maybe --no-decorate?
