### ISSUE TITLE
Try to replicate the original Subject and use it in email

### ISSUE THREAD

**Issue by kvalo** [kvalo/pwcli#5]
Patchwork removes "[PATCH]" (and varitions of it) from the Subject and doesn't provide the original Subject via XML-RPC interface. Using modified Subject makes the threading look ugly in the summary emails so try to replicate back the original Subject. Should be possible by investigation how patchwork strips the Subject.

**Comment by jmberg** [comment]
If you use the REST API (https://patchwork.readthedocs.io/en/latest/api/rest/schemas/v1.2/#get--api-1.2-patches-id-) you get an 'mbox' link (e.g. https://patchwork.kernel.org/patch/11793109/mbox/) and in the mbox the subject is maintained, not mangled.

**Comment by jmberg** [comment]
Actually, it looks like even in the returned JSON on (e.g. https://patchwork.kernel.org/api/1.0/patches/11793109/) it's actually fine in the headers.subject.

So just use json['headers']['subject'] instead of json['name']?

**Comment by kvalo** [comment]
This is fixed now. IIRC I didn't make any changes in pwcli, this was fixed in the server side.
